### PR TITLE
token-cli: load config if exists without -C

### LINKED ISSUE #3630: spl-token create-token: "Attempt to debit an account but found no record of a prior credit."
`spl-token create-token` works at tag token-cli-v2.0.17 but fails in master (e988b163bbe6033cbebaa6e08b3e1203273928ef).

The error in master is:

```
Error: Client(ClientError { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: "Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(AccountNotFound), logs: Some([]), accounts: None, units_consumed: Some(0), return_data: None }) }) })
```

git bisect suggests the offending commit is cc2739fce19537ae454ee513da96698d79362c53.

### PR DESCRIPTION
**Pull request by 2501babe**
looks like this branch of the if statement got dropped on the floor in a rebase because me and the outside contributor were working on the code at the same time. without it, `config.yml` is never loaded

closes #3630

### CODE REVIEW

**Comment by 2501babe** [comment]
@CriesofCarrots im leaving most of my reviews until jon comes back but this is a pretty straightforward regression, if you wouldnt mind taking a look

File: token/cli/src/config.rs [hunk 1]
```diff
@@ -57,6 +57,8 @@ impl<'a> Config<'a> {
                 eprintln!("error: Could not find config file `{}`", config_file);
                 exit(1);
             })
+        } else if let Some(config_file) = &*solana_cli_config::CONFIG_FILE {
```
Comment (CriesofCarrots) [inline token/cli/src/config.rs:60]: Any particular reason you did this instead of the original `if let Some(ref config_file) = *solana_cli_config::CONFIG_FILE`?

**Review by CriesofCarrots — APPROVED** [review]
Happy to pull in to review whatever!

File: token/cli/src/config.rs (hunk 1 above)
Comment (2501babe) [reply token/cli/src/config.rs:60]: oh, no i just hadnt seen that form anywhere else. i can change it back if you prefer

Comment (CriesofCarrots) [reply token/cli/src/config.rs:60]: Naw, I don’t feel strongly, just curious.
