### PR TITLE
Fix Token program ESM exports

### LINKED ISSUE #3502: Error to import `@solana/spl-token` ESM module
Importing `@solana/spl-token` occurs errors like below such as next.js or browser.
```
error - ../node_modules/.pnpm/@solana+spl-token@0.3.1/node_modules/@solana/spl-token/lib/esm/extensions/extensionType.mjs:5:0
Module not found: Can't resolve './memoTransfer.mjs'

Import trace for requested module:
../node_modules/.pnpm/@solana+spl-token@0.3.1/node_modules/@solana/spl-token/lib/esm/extensions/index.mjs
../node_modules/.pnpm/@solana+spl-token@0.3.1/node_modules/@solana/spl-token/lib/esm/index.mjs
./src/pages/index.tsx
```

It seems to need that some ts files in `src` would be updated like below.

```diff
diff --git a/src/extensions/extensionType.ts b/src/extensions/extensionType.ts
index cbc0f4760f6c325d092d5d4b0441046b93b1d0f9..e4b4a3aa267b26cfe83b02292bd74219434343a5 100644
--- a/src/extensions/extensionType.ts
+++ b/src/extensions/extensionType.ts
@@ -2,11 +2,11 @@ import { ACCOUNT_SIZE } from '../state/account';
 import { Mint, MINT_SIZE } from '../state/mint';
 import { MULTISIG_SIZE } from '../state/multisig';
 import { ACCOUNT_TYPE_SIZE } from './accountType';
-import { MEMO_TRANSFER_SIZE } from './memoTransfer';
-import { DEFAULT_ACCOUNT_STATE_SIZE } from './defaultAccountState';
+import { MEMO_TRANSFER_SIZE } from './memoTransfer/index';
+import { DEFAULT_ACCOUNT_STATE_SIZE } from './defaultAccountState/index';
 import { MINT_CLOSE_AUTHORITY_SIZE } from './mintCloseAuthority';
 import { IMMUTABLE_OWNER_SIZE } from './immutableOwner';
-import { TRANSFER_FEE_CONFIG_SIZE, TRANSFER_FEE_AMOUNT_SIZE } from './transferFee';
+import { TRANSFER_FEE_CONFIG_SIZE, TRANSFER_FEE_AMOUNT_SIZE } from './transferFee/index';
 import { NON_TRANSFERABLE_SIZE } from './nonTransferable';
 import { INTEREST_BEARING_MINT_CONFIG_STATE_SIZE } from './interestBearingMint/state';
 
diff --git a/src/extensions/index.ts b/src/extensions/index.ts
index 3803bb7d9e28a54a458f24be156eebe6f28cd7e9..6aea395449cda46555741dad2f8393aa6915fcdb 100644
--- a/src/extensions/index.ts
+++ b/src/extensions/index.ts
@@ -4,6 +4,6 @@ export * from './extensionType';
 export * from './memoTransfer/index';
 export * from './mintCloseAuthority';
 export * from './immutableOwner';
-export * from './interestBearingMint';
+export * from './interestBearingMint/index';
 export * from './nonTransferable';
 export * from './transferFee/index';
diff --git a/src/extensions/interestBearingMint/actions.ts b/src/extensions/interestBearingMint/actions.ts
index 552aadfafa0e2b5f079a0e50b7dfe0c8fecd155d..f6348d8b43c297db6d845efe9bbb1ca5997a80b7 100644
--- a/src/extensions/interestBearingMint/actions.ts
+++ b/src/extensions/interestBearingMint/actions.ts
@@ -10,7 +10,7 @@ import {
 } from '@solana/web3.js';
 import { getSigners } from '../../actions/internal';
 import { TOKEN_2022_PROGRAM_ID } from '../../constants';
-import { createInitializeMintInstruction } from '../../instructions';
+import { createInitializeMintInstruction } from '../../instructions/index';
 import { ExtensionType, getMintLen } from '../extensionType';
 import {
     createInitializeInterestBearingMintInstruction,
diff --git a/src/extensions/interestBearingMint/instructions.ts b/src/extensions/interestBearingMint/instructions.ts
index ca330ce5f74a942f2d5c68147e29b1c178cba267..e1a393a34690597460fa57b1d66eeaf8116e01af 100644
--- a/src/extensions/interestBearingMint/instructions.ts
+++ b/src/extensions/interestBearingMint/instructions.ts
@@ -2,7 +2,7 @@ import { struct, s16, u8 } from '@solana/buffer-layout';
 import { publicKey } from '@solana/buffer-layout-utils';
 import { PublicKey, Signer, TransactionInstruction } from '@solana/web3.js';
 import { TOKEN_2022_PROGRAM_ID } from '../../constants';
-import { TokenInstruction } from '../../instructions';
+import { TokenInstruction } from '../../instructions/index';
 import { addSigners } from '../../instructions/internal';
 
 export enum InterestBearingMintInstruction {
```

### PR DESCRIPTION
**Pull request by jordansexton**
This is the second of two PRs to address https://github.com/solana-labs/solana-program-library/issues/3502, this one for the Token program JS (https://github.com/solana-labs/solana-program-library/pull/3507 for Memo, which it builds on top of). This fixes the issues that build systems have with .mjs files by exporting .js files. It also restructures the project to be similar to Wallet Adapter / the TypeScript monorepo template I've been using.

Fixes #3502

### CODE REVIEW

File: token/js/src/actions/approve.ts [hunk 1]
```diff
@@ -1,15 +1,8 @@
...
-    TransactionSignature,
-} from '@solana/web3.js';
-import { TOKEN_PROGRAM_ID } from '../constants';
-import { createApproveInstruction } from '../instructions/index';
-import { getSigners } from './internal';
+import type { ConfirmOptions, Connection, PublicKey, Signer, TransactionSignature } from '@solana/web3.js';
+import { sendAndConfirmTransaction, Transaction } from '@solana/web3.js';
+import { TOKEN_PROGRAM_ID } from '../constants.js';
+import { createApproveInstruction } from '../instructions/approve.js';
+import { getSigners } from './internal.js';
```
Comment (jordansexton) [inline token/js/src/actions/approve.ts:5]: What's changing across the project is that we are using imports with explicit .js extensions, and we're limiting use of index imports to descendants of any given directory. Each instruction can be imported directly without circular references.

File: token/js/package.json [hunk 2]
```diff
@@ -1,74 +1,86 @@
...
+        "deploy:docs": "npm run docs && gh-pages --dist token/js --dotfiles"
+    },
+    "peerDependencies": {
+        "@solana/web3.js": "^1.20.0"
     },
     "dependencies": {
         "@solana/buffer-layout": "^4.0.0",
         "@solana/buffer-layout-utils": "^0.2.0",
-        "@solana/web3.js": "^1.41.0"
+        "@solana/spl-memo": "^0.2.0",
```
Comment (joncinque) [inline token/js/package.json:57]: Shouldn't this be a dev dependency? Also, may as well specify 0.3.0 for the next version, right?

File: token/js/src/actions/approve.ts (hunk 1 above)
Comment (joncinque) [reply token/js/src/actions/approve.ts:5]: what's the reason for explicit .js extensions? Is that specifically for those build systems?  And what do you mean by

> we're limiting use of index imports to descendants of any given directory

I didn't notice any differences in the import statements in index files

**Review by joncinque — COMMENTED** [review]
Just the one question, but otherwise looks good. Also, the node runner for the GitHub action needs to be updated to version 16

File: token/js/package.json (hunk 2 above)
Comment (jordansexton) [reply token/js/package.json]: This is an unbundled runtime dependency, so not a dev dependency. But I did change the version to 0.2.1 to match the next one.

Comment (joncinque) [reply token/js/package.json]: How is it a runtime dependency? It's only ever used in a test

File: token/js/src/actions/approve.ts (hunk 1 above)
Comment (jordansexton) [reply token/js/src/actions/approve.ts:5]: > what's the reason for explicit .js extensions? Is that specifically for those build systems?

TypeScript (somewhat infamously) [will not add `.js` extensions to imports](https://github.com/microsoft/TypeScript/issues/16577) when compiling, but _will_ resolve `.js` files to `.ts` files.

Next.js, Webpack 5, and some other build systems won't automatically resolve `.mjs` files when importing without an extension, which is what is causing https://github.com/solana-labs/solana-program-library/issues/3502.

Explicit declaring the file extensions here is the way to get them explicitly declared in the output. I will probably need to add an eslint rule to enforce this.

> I didn't notice any differences in the import statements in index files

For example, this file change we are commenting on replaces:

```ts
import { createApproveInstruction } from '../instructions/index';
```
with 
```ts
import { createApproveInstruction } from '../instructions/approve.js';
```

Instead of using an index import, which would need to become `'../instructions/index.js'` anyway, we just import from the specific file we need. This practice is generally good because it helps avoid circular references. Plus, we don't need to resolve the whole index to get one or two exports from it.

Comment (joncinque) [reply token/js/src/actions/approve.ts:5]: Ah gotcha, I missed that part, thanks for all the explanation!

File: token/js/package.json (hunk 2 above)
Comment (jordansexton) [reply token/js/package.json]: Oh, I was mistaken. I thought it was used by the new `MemoTransferInstruction` but it isn't. Fixed!

File: token/js/src/actions/approve.ts (hunk 1 above)
Comment (jordansexton) [reply token/js/src/actions/approve.ts:5]: Np!

**Comment by jordansexton** [comment]
> Also, the node runner for the GitHub action needs to be updated to version 16

Done, thanks! Running now.

**Review by joncinque — APPROVED** [review]

**Comment by jordansexton** [comment]
Published in @solana/spl-token@0.3.2

**Comment by raymondfeng** [comment]
This change is breaking TypeScript node.js import of `@solana/spl-token`:

```
✖ ERROR: Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@solana/spl-token/lib/cjs/index.js from solana.client.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in node_modules/@solana/spl-token/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**Comment by jordansexton** [comment]
@raymondfeng I'm not sure what `solana.client.js` or where this error is coming from. Can you open a new issue with details on how to reproduce the issue?
