### PR TITLE
SPL errors from hashes

### LINKED ISSUE #5042: [Token-2022] Transfer hook interface error reporting
## Issue

There is currently an issue on how errors originating from the `transfer-hook-interface` are reported on the logs/client. Since the interface has its own `TransferHookError` error enum with overlapping codes (indices) with `TokenError` error enum, errors originating from the `transfer-hook-interface` get "translated" to a `TokenError` with the same code.

For example, if the extra accounts metas account is missing:
```rust
let validation_pubkey = get_extra_account_metas_address(mint_info.key, program_id);
let validation_info = additional_accounts
    .iter()
    .find(|&x| *x.key == validation_pubkey)
    .ok_or(TransferHookError::IncorrectAccount)?;
```

The error gets translated as `Lamport balance below rent-exempt threshold`, since both `TransferHookError::IncorrectAccount` and `TokenError::NotRentExempt` have an error code (index) of `0`.

A similar situation will happen if one of the accounts required for the transfer-hook program on-chain is missing: 
```rust
let account_info = account_infos
    .iter()
    .find(|&x| *x.key == account_meta.pubkey)
    .ok_or(AccountResolutionError::IncorrectAccount)?
    .clone();
cpi_account_infos.push(account_info);
```

`AccountResolutionError::IncorrectAccount` has an error code (index) of `0`.

Below is a sample output:
image

## Potential Solution

Errors originated from `transfer-hook-interface` and `tlv-account-resolution` could be mapped to individual `TokenError`s specific to the situation where they are generated – e.g., similar to how there seems to be errors for the `CpiGuard` and `ConfidentialTransfer`.

### PR DESCRIPTION
**Pull request by buffalojoec**
This PR adds unique, custom error codes to every error in SPL libraries - including the two interfaces `transfer-hook` and `token-metadata`.

The ability to derive unique `u32` error codes from hash inputs is powered by these changes to the `spl-program-error` crate, which simply hashes the following combination of inputs and takes bytes 13 through 16 as the little-endian `u32`:

```text
"spl_program_error:" + <enum name> + ":" + <variant name>
```

This creates unique error codes for each error, as requested in [this comment](https://github.com/solana-labs/solana-program-library/pull/5168#issuecomment-1697853488)

Closes #5042 
Solves discussions in #5168

### CODE REVIEW

File: token/transfer-hook-interface/src/error.rs [hunk 1]
```diff
@@ -1,17 +1,9 @@
...
-        msg,
-        program_error::{PrintProgramError, ProgramError},
-    },
-    thiserror::Error,
-};
+use spl_program_error::*;
 
 /// Errors that may be returned by the interface.
-#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
+#[spl_program_error(hash_error_codes = true)]
```
Comment (joncinque) [inline token/transfer-hook-interface/src/error.rs:6]: :tada:

File: libraries/program-error/derive/src/macro_impl.rs [hunk 2]
```diff
@@ -114,3 +143,37 @@ pub fn spl_program_error(input: ItemEnum) -> proc_macro2::TokenStream {
...
+        let variant_ident = &variant.ident;
+        let discriminant = u32_from_hash(enum_ident, variant_ident);
+        let eq = Token![=](Span::call_site());
+        let expr = Expr::Lit(ExprLit {
+            attrs: Vec::new(),
+            lit: Lit::Int(LitInt::new(&discriminant.to_string(), Span::call_site())),
+        });
+        variant.discriminant = Some((eq, expr));
+    }
+}
```
Comment (joncinque) [inline libraries/program-error/derive/src/macro_impl.rs:164]: This is really neat!

**Review by joncinque — COMMENTED** [review]
The implementation looks perfect! I did just realize though... we'll need a way for someone at the top-level to get more information about the error, since they're essentially random numbers :sweat: 

Ok, hear me out, what if instead of giving *each error* a random number, we give the *first* error a random hashed number of `namespace:error_name`, and everything counts up from there? That way someone just needs to find out that first number, which we force people to add to the source code somewhere to make it easier to discover, similar to `solana-frozen-abi`, ie:

```
#[spl_program_error(hash_error_codes = true, error_start = 42)]
pub enum MyError {
    OhNoes,
}
```

Where `42` is `hash('spl_program_error:MyError')[13..17]`. If it's incorrect, the macro tells you what number to set as `error_start`.

We could maybe condense those two into one arg, but I can't come up with any good names. Maybe just have `expected_error_start`? Or expose a new macro, like `spl_program_error_with_unique_error_codes` which does the hashing and also takes in the expected start number? These names all stink, so I'll noodle on something better.

**Comment by joncinque** [comment]
> On the topic of collisions, I felt like it was probably also overkill, but I have one particular concern about a hash randomly resulting in, say [1, 0, 0, 0] and colliding with (literally any) program errors. For this reason I suggest we lean toward a fixed 9 on the MSB and take only bytes 13, 14, and 15 from the hash. wdyt?

Ah right, that's a good point. Rather than remove a whole byte from the randomness, how about we just make sure that the number is >= 256 to be totally safe? and if it happens to be 0 <= x < 256, just shift over 1 byte until you get to a valid set of bytes.

> It smells a bit like a macro anti-pattern to me

If you have a better way of surfacing that number easily for people looking at the source, I'm game! But I couldn't come up with anything else

**Comment by buffalojoec** [comment]
> > On the topic of collisions, I felt like it was probably also overkill, but I have one particular concern about a hash randomly resulting in, say [1, 0, 0, 0] and colliding with (literally any) program errors. For this reason I suggest we lean toward a fixed 9 on the MSB and take only bytes 13, 14, and 15 from the hash. wdyt?

smh, I meant `256` not `9`

> Ah right, that's a good point. Rather than remove a whole byte from the randomness, how about we just make sure that the number is >= 256 to be totally safe? and if it happens to be 0 <= x < 256, just shift over 1 byte until you get to a valid set of bytes.

Which number are you referring to? The entire `u32` integer itself? In my opinion we want to clear at least 5000 for Anchor errors, and likely even go a little further just to be safe for people who like to categorize with leading digits. Say, `10_000` or `100_000`?

> > It smells a bit like a macro anti-pattern to me
> 
> If you have a better way of surfacing that number easily for people looking at the source, I'm game! But I couldn't come up with anything else

Nah I think it's okay. Unless I find some Rustaceans barking about it online, it's going in

**Comment by joncinque** [comment]
> Which number are you referring to? The entire u32 integer itself? In my opinion we want to clear at least 5_000 for Anchor errors, and likely even go a little further just to be safe for people who like to categorize with leading digits. Say, 10_000 or 100_000?

Sorry, yeah I mean the whole 4 bytes interpreted as a little-endian u32. Does Anchor start at 5000 for all programs? That seems very odd. If that's the case, we can just do 6000 or something, right? And that's already being plenty generous I'd say. If people use their own start, that's similar to just grinding a bunch of error names until you get something you like.

**Comment by buffalojoec** [comment]
> > Which number are you referring to? The entire u32 integer itself? In my opinion we want to clear at least 5_000 for Anchor errors, and likely even go a little further just to be safe for people who like to categorize with leading digits. Say, 10_000 or 100_000?
> 
> Sorry, yeah I mean the whole 4 bytes interpreted as a little-endian u32. Does Anchor start at 5000 for all programs? That seems very odd. If that's the case, we can just do 6000 or something, right? And that's already being plenty generous I'd say. If people use their own start, that's similar to just grinding a bunch of error names until you get something you like.

They use the first digit as a category https://docs.rs/anchor-lang/latest/anchor_lang/error/enum.ErrorCode.html
and then users start at 6000 https://docs.rs/anchor-lang/latest/anchor_lang/error/constant.ERROR_CODE_OFFSET.html

I have 10,000 in my latest commit, I guess we could get away with 7,000 ?

File: libraries/program-error/derive/src/macro_impl.rs [hunk 3]
```diff
@@ -114,3 +144,53 @@ pub fn spl_program_error(input: ItemEnum) -> proc_macro2::TokenStream {
...
+
+/// Hashes the `SPL_ERROR_HASH_NAMESPACE` constant, the enum name and variant
+/// name and returns four middle bytes (13 through 16) as a u32.
+fn u32_from_hash(enum_ident: &Ident, variant_ident: &Ident) -> u32 {
+    let hash_input = format!(
+        "{}:{}:{}",
+        SPL_ERROR_HASH_NAMESPACE, enum_ident, variant_ident
+    );
+
+    // We don't want our error code to start at any number below `10_0000`!
```
Comment (joncinque) [inline libraries/program-error/derive/src/macro_impl.rs:182]: nit:
```suggestion
    // We don't want our error code to start at any number below `SPL_ERROR_HASH_MIN_VALUE`!
```

File: libraries/program-error/derive/src/macro_impl.rs [hunk 4]
```diff
@@ -114,3 +144,53 @@ pub fn spl_program_error(input: ItemEnum) -> proc_macro2::TokenStream {
...
+    if discriminant == error_code_start {
+        let eq = Token![=](Span::call_site());
+        let expr = Expr::Lit(ExprLit {
+            attrs: Vec::new(),
+            lit: Lit::Int(LitInt::new(&discriminant.to_string(), Span::call_site())),
+        });
+        first_variant.discriminant = Some((eq, expr));
+    } else {
+        panic!(
+            "Error code start value from hash is {}. Update your macro attribute.",
```
Comment (joncinque) [inline libraries/program-error/derive/src/macro_impl.rs:168]: Let's tell people *exactly* what to do
```suggestion
            "Error code start value from hash must be {0}. Update your macro use to `#[spl_program_error(hash_error_code_start = {0})]`.",
```

File: libraries/program-error/derive/src/lib.rs [hunk 5]
```diff
@@ -14,39 +14,72 @@
...
+/// Optionally, you can add `hash_error_code_start: u32` argument to create
+/// a unique `u32` _starting_ error codes from the names of the enum variants.
+/// Notes:
+/// - The _error_ variant will start at this value, and the rest will be
+/// incremented by one
+/// - The value provided is only for code readability, the actual error code
+/// will be a hash of the input string and is checked against your input
+///
+/// Syntax: `#[spl_program_error(hash_error_code_start = 1275525928)]`
+/// Hash Input: `spl_program_error:<enum name>:<variant name>`
```
Comment (joncinque) [inline libraries/program-error/derive/src/lib.rs:76]: I might be missing something, but is there a reason to include the variant name? I'm thinking it would be clearer to just use the enum name.

**Review by joncinque — COMMENTED** [review]
Just few tiny last little questions, this is extremely close!

File: libraries/program-error/derive/src/lib.rs (hunk 5 above)
Comment (buffalojoec) [reply libraries/program-error/derive/src/lib.rs:76]: Yeah good point, probably not needed now that we're only hashing variant 0

File: libraries/program-error/derive/src/macro_impl.rs [hunk 6]
```diff
@@ -1,32 +1,52 @@
...
+    proc_macro2::Span,
+    quote::quote,
+    syn::{
+        punctuated::Punctuated, token::Comma, Expr, ExprLit, Ident, ItemEnum, Lit, LitInt, LitStr,
+        Token, Variant,
+    },
+};
+
+const SPL_ERROR_HASH_NAMESPACE: &str = "spl_program_error";
+const SPL_ERROR_HASH_MIN_VALUE: u32 = 10_0000;
```
[the remark this answers is not in the document]
Comment (buffalojoec) [reply libraries/program-error/derive/src/macro_impl.rs:14]: Some people must have said "but `u32` is huuuuge!"

**Comment by buffalojoec** [comment]
Comments resolved!

This is a breaking change for anything using these libraries downstream. I'm thinking:
- `spl-program-error`: `1.0.0` or `0.3.0` if we want to keep it in development
- Any downstream crates: Bump minor version

wdyt?

File: libraries/program-error/derive/src/macro_impl.rs [hunk 7]
```diff
@@ -11,7 +11,7 @@ use {
 };
 
 const SPL_ERROR_HASH_NAMESPACE: &str = "spl_program_error";
-const SPL_ERROR_HASH_MIN_VALUE: u32 = 10_0000;
+const SPL_ERROR_HASH_MIN_VALUE: u32 = 7_0000;
```
Comment (joncinque) [inline libraries/program-error/derive/src/macro_impl.rs:14]: Haha I just realized that this has an extra 0, should be `7_000`. Good thing we have multiple rounds of reviews

**Comment by joncinque** [comment]
> This is a breaking change for anything using these libraries downstream

Sorry, maybe I'm missing something, but how is this change breaking? It passes CI without any changes to other libraries that are using it currently

File: libraries/program-error/derive/src/macro_impl.rs (hunk 7 above)
Comment (buffalojoec) [reply libraries/program-error/derive/src/macro_impl.rs:14]: Ah! my bad

**Comment by buffalojoec** [comment]
> > This is a breaking change for anything using these libraries downstream
> 
> Sorry, maybe I'm missing something, but how is this change breaking? It passes CI without any changes to other libraries that are using it currently

Is it not _technically_ breaking since the underlying error codes are changing?

CI is passing because I included changes to the tests where the expected error changed.

For example, anyone expecting `TransferHookError::IncorrectAccount` is now getting `AccountResolutionError::IncorrectAccount`, and furthermore anyone expecting some `u32` like `1` is now getting `13498579` or something wild.

**Comment by joncinque** [comment]
> Is it not technically breaking since the underlying error codes are changing?

But that's only if you use `hash_error_code_start`, right?

**Comment by buffalojoec** [comment]
> > Is it not technically breaking since the underlying error codes are changing?
> 
> But that's only if you use `hash_error_code_start`, right?

I'm thinking about if I'm working with `spl_token_2022` and I'm expecting certain codes from, say transfer hook helpers. Also `spl_token_client` for that matter

**Review by joncinque — APPROVED** [review]
Looks good!

hash

**Comment by buffalojoec** [comment]
Lmao Lennon would approve
