### PR TITLE
token js: create new offchain helper

### LINKED ISSUE #6064: Transfer Hook: Off-chain and on-chain helpers are resolving keys incorrectly
#### Problem
Token2022's off-chain and on-chain helpers for adding the necessary extra account metas for a transfer instruction that requires a transfer hook are missing a crucial step.

**Note:** This crucial step is missing _only_ from the helpers, thus the on-chain program itself needs no change.

At the bottom of this issue is a test. In it, we're going to build instructions with extra account metas in three ways:
- Adding extra metas to a `TransferChecked` instruction using the Token2022 off-chain helper
- Adding extra metas to an `Execute` instruction using the TLV Account Resolution library's `add_to_instruction`
- Adding extra metas to an `Execute` CPI instruction using the TLV Account Resolution library's `add_to_cpi_instruction`

As you can probably infer, the issue is that we are adding the extra metas to a **transfer** instruction, rather than an `Execute` instruction.

Consider the instruction keys for `TransferChecked` (simplified):

0. [w] Source
1. [] Mint
2. [w] Destination
3. [s] Owner

Now consider the instruction keys as defined in the [SPL Transfer Hook Interface's `Execute` instruction](https://github.com/solana-labs/solana-program-library/blob/f36c2fb5a24bd87e04c60a509aec94304798c1a3/token/transfer-hook/interface/src/instruction.rs#L22-L34):

0. [] Source
1. [] Mint
2. [] Destination
3. [] Owner
4. [] Validation account

As you can see, `Execute` requires the validation (extra metas) account, while `TransferChecked` does not.

When extra account metas are hard-coded addresses, ie. `ExtraAccountMeta::new_with_pubkey(..)`, this is not an issue. However, once any extra account meta uses seed configurations that point to other account keys in the list, this difference in account keys bungles the whole resolution.

The problem here is that, at the time of account resolution, the list of account keys for a transfer instruction and the list of account keys for an `Execute` instruction will yield entirely different resolutions.

For example, if I have a PDA that's based off of the account at index 4, that will be two different accounts depending on the instruction. No bueno.

Consider the test.

```rust
const TRANSFER_HOOK_PROGRAM_ID: Pubkey = Pubkey::new_from_array([1; 32]);

const MINT_PUBKEY: Pubkey = Pubkey::new_from_array([2; 32]);

const MOCK_MINT_STATE: [u8; 234] = [
    0, 0, 0, 0, // COption (4): None = 0
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, // Mint authority (32)
    0, 0, 0, 0, 0, 0, 0, 0, // Supply (8)
    0, // Decimals (1)
    1, // Is initialized (1)
    0, 0, 0, 0, // COption (4): None = 0
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, // Freeze authority (32)
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // Padding (83)
    1, // Account type (1): Mint = 1
    14, 0, // Extension type (2): Transfer hook = 14
    64, 0, // Extension length (2): 64
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, // Authority (32)
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, // Transfer hook program ID (32)
];

const MOCK_EXTRA_METAS_STATE: [u8; 86] = [
    105, 37, 101, 197, 75, 251, 102, 26, // Discriminator for `ExecuteInstruction` (8)
    74, 0, 0, 0, // Length of pod slice (4): 74
    2, 0, 0, 0, // Count of account metas (4): 2
    1, // First account meta discriminator (1): PDA = 1
    3, 0, // First seed: Account key at index 0 (2)
    3, 1, // Second seed: Account key at index 1 (2)
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, // No more seeds (28)
    0, // First account meta is signer (1): false = 0
    0, // First account meta is writable (1): false = 0
    1, // Second account meta discriminator (1): PDA = 1
    3, 4, // First seed: Account key at index 4 (2)
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, // No more seeds (30)
    0, // Second account meta is signer (1): false = 0
    0, // Second account meta is writable (1): false = 0
];

async fn mock_fetch_account_data_fn(address: Pubkey) -> AccountDataResult {
    if address == MINT_PUBKEY {
        Ok(Some(MOCK_MINT_STATE.to_vec()))
    } else if address
        == get_extra_account_metas_address(&MINT_PUBKEY, &TRANSFER_HOOK_PROGRAM_ID)
    {
        Ok(Some(MOCK_EXTRA_METAS_STATE.to_vec()))
    } else {
        Ok(None)
    }
}

#[tokio::test]
async fn test_resolve_extra_transfer_account_metas() {
    let spl_token_2022_program_id = crate::id();
    let transfer_hook_program_id = TRANSFER_HOOK_PROGRAM_ID;

    let source_pubkey = Pubkey::new_unique();
    let mut source_data = vec![0; 165]; // Mock
    let mut source_lamports = 0; // Mock
    let source_account_info = AccountInfo::new(
        &source_pubkey,
        false,
        true,
        &mut source_lamports,
        &mut source_data,
        &spl_token_2022_program_id,
        false,
        0,
    );

    let mint_pubkey = MINT_PUBKEY;
    let mut mint_data = MOCK_MINT_STATE.to_vec();
    let mut mint_lamports = 0; // Mock
    let mint_account_info = AccountInfo::new(
        &mint_pubkey,
        false,
        true,
        &mut mint_lamports,
        &mut mint_data,
        &spl_token_2022_program_id,
        false,
        0,
    );

    let destination_pubkey = Pubkey::new_unique();
    let mut destination_data = vec![0; 165]; // Mock
    let mut destination_lamports = 0; // Mock
    let destination_account_info = AccountInfo::new(
        &destination_pubkey,
        false,
        true,
        &mut destination_lamports,
        &mut destination_data,
        &spl_token_2022_program_id,
        false,
        0,
    );

    let authority_pubkey = Pubkey::new_unique();
    let mut authority_data = vec![]; // Mock
    let mut authority_lamports = 0; // Mock
    let authority_account_info = AccountInfo::new(
        &authority_pubkey,
        false,
        true,
        &mut authority_lamports,
        &mut authority_data,
        &system_program::ID,
        false,
        0,
    );

    let validate_state_pubkey = get_extra_account_metas_address(&mint_pubkey, &transfer_hook_program_id);

    let extra_meta_1_pubkey = Pubkey::find_program_address(
        &[
            &source_pubkey.to_bytes(), // Account key at index 0
            &mint_pubkey.to_bytes(),   // Account key at index 1
        ],
        &transfer_hook_program_id,
    )
    .0;
    let mut extra_meta_1_data = vec![]; // Mock
    let mut extra_meta_1_lamports = 0; // Mock
    let extra_meta_1_account_info = AccountInfo::new(
        &extra_meta_1_pubkey,
        false,
        true,
        &mut extra_meta_1_lamports,
        &mut extra_meta_1_data,
        &transfer_hook_program_id,
        false,
        0,
    );

    let extra_meta_2_pubkey = Pubkey::find_program_address(
        &[
            &validate_state_pubkey.to_bytes(), // Account key at index 4
        ],
        &transfer_hook_program_id,
    )
    .0;
    let mut extra_meta_2_data = vec![]; // Mock
    let mut extra_meta_2_lamports = 0; // Mock
    let extra_meta_2_account_info = AccountInfo::new(
        &extra_meta_2_pubkey,
        false,
        true,
        &mut extra_meta_2_lamports,
        &mut extra_meta_2_data,
        &transfer_hook_program_id,
        false,
        0,
    );

    let mut validate_state_data = MOCK_EXTRA_METAS_STATE.to_vec();
    let mut validate_state_lamports = 0; // Mock
    let validate_state_account_info = AccountInfo::new(
        &validate_state_pubkey,
        false,
        true,
        &mut validate_state_lamports,
        &mut validate_state_data,
        &transfer_hook_program_id,
        false,
        0,
    );

    // First use the resolve function to add the extra account metas to the
    // transfer instruction from offchain
    let mut offchain_transfer_instruction = crate::instruction::transfer_checked(
        &spl_token_2022_program_id,
        &source_pubkey,
        &mint_pubkey,
        &destination_pubkey,
        &authority_pubkey,
        &[],
        2,
        9,
    )
    .unwrap();

    resolve_extra_transfer_account_metas(
        &mut offchain_transfer_instruction,
        mock_fetch_account_data_fn,
        &mint_pubkey,
    )
    .await
    .unwrap();

    // Then use the offchain function to add the extra account metas to the
    // _execute_ instruction from offchain
    let mut offchain_execute_instruction = spl_transfer_hook_interface::instruction::execute(
        &transfer_hook_program_id,
        &source_pubkey,
        &mint_pubkey,
        &destination_pubkey,
        &authority_pubkey,
        &validate_state_pubkey,
        0,
    );

    ExtraAccountMetaList::add_to_instruction::<ExecuteInstruction, _, _>(
        &mut offchain_execute_instruction,
        mock_fetch_account_data_fn,
        &MOCK_EXTRA_METAS_STATE,
    )
    .await
    .unwrap();

    // Finally, use the onchain function to add the extra account metas to
    // the _execute_ CPI instruction from onchain
    let mut onchain_execute_cpi_instruction = spl_transfer_hook_interface::instruction::execute(
        &transfer_hook_program_id,
        &source_pubkey,
        &mint_pubkey,
        &destination_pubkey,
        &authority_pubkey,
        &validate_state_pubkey,
        0,
    );
    let mut onchain_execute_cpi_account_infos = vec![
        source_account_info.clone(),
        mint_account_info.clone(),
        destination_account_info.clone(),
        authority_account_info.clone(),
        validate_state_account_info.clone(),
    ];
    let all_account_infos = &[
        source_account_info.clone(),
        mint_account_info.clone(),
        destination_account_info.clone(),
        authority_account_info.clone(),
        validate_state_account_info.clone(),
        extra_meta_1_account_info.clone(),
        extra_meta_2_account_info.clone(),
    ];

    ExtraAccountMetaList::add_to_cpi_instruction::<ExecuteInstruction>(
        &mut onchain_execute_cpi_instruction,
        &mut onchain_execute_cpi_account_infos,
        &MOCK_EXTRA_METAS_STATE,
        all_account_infos,
    )
    .unwrap();

    // Now let's evaluate the different lists of keys

    // The two `Execute` instructions should have the same accounts
    assert_eq!(
        offchain_execute_instruction.accounts,
        onchain_execute_cpi_instruction.accounts,
    );

    // However, the transfer instruction is going to be missing the
    // the validation account at index 4
    assert_ne!(
        offchain_transfer_instruction.accounts,
        offchain_execute_instruction.accounts,
    );
    assert_ne!(
        offchain_transfer_instruction.accounts[4].pubkey,
        validate_state_pubkey,
    );

    // Even though both execute instructions have the validation account
    // at index 4
    assert_eq!(
        offchain_execute_instruction.accounts[4].pubkey,
        validate_state_pubkey,
    );
    assert_eq!(
        onchain_execute_cpi_instruction.accounts[4].pubkey,
        validate_state_pubkey,
    );

    // Despite the differences in indices, we're also going to have entirely
    // different PDAs in each list, and this is the issue
    assert_ne!(
        offchain_transfer_instruction.accounts[4].pubkey,
        extra_meta_1_pubkey,
    );
    assert_eq!(
        offchain_execute_instruction.accounts[5].pubkey,
        extra_meta_1_pubkey,
    );
    assert_eq!(
        onchain_execute_cpi_instruction.accounts[5].pubkey,
        extra_meta_1_pubkey,
    );
    assert_ne!(
        offchain_transfer_instruction.accounts[5].pubkey,
        extra_meta_2_pubkey,
    );
    assert_eq!(
        offchain_execute_instruction.accounts[6].pubkey,
        extra_meta_2_pubkey,
    );
    assert_eq!(
        onchain_execute_cpi_instruction.accounts[6].pubkey,
        extra_meta_2_pubkey,
    );

    // For even more verbosity
    assert!(offchain_transfer_instruction
        .accounts
        .iter()
        .find(|account_meta| account_meta.pubkey == extra_meta_1_pubkey)
        .is_none());
    assert!(offchain_transfer_instruction
        .accounts
        .iter()
        .find(|account_meta| account_meta.pubkey == extra_meta_2_pubkey)
        .is_none());
}
```

#### Proposed Solution
We should be able to insert a few lines of code into the helpers that simply converts a transfer instruction into an `Execute` instruction _before_ resolving the extra account metas.

Since anyone storing extra account meta configs should be considering the list of accounts as it will arrive in their Transfer Hook program's `Execute` instruction, it makes sense to resolve for `Execute`.

After all, the main problem we have here is that we're asking TLV Account Resolution to resolve the extra account metas for an `Execute` instruction, but we're not actually feeding it a valid `Execute` instruction.

### PR DESCRIPTION
**Pull request by buffalojoec**
This is the final PR to round off the changes required to fix #6064.

Previously, the offchain helpers for adding extra metas to instructions have
been replaced with new ones in the SPL Transfer Hook interface and Token2022.

This PR follows suit and adds a new helper to SPL Token JS.

The new helper, `addExtraAccountMetasForExecute(..)`, mirrors the Rust helper in
SPL Transfer Hook interface, requiring the parameters for an
`ExecuteInstruction` to be passed into the function directly.

This change also adds a public function for creating an `ExecuteInstruction`, in
case developers wish to create such an instruction for directly sending
instructions to their transfer hook program.

These existing functions have been updated to use the new helper:
- `createTransferCheckedWithTransferHookInstruction(..)`
- `createTransferCheckedWithFeeAndTransferHookInstruction(..)`

Closes #6064

### CODE REVIEW

**Comment by buffalojoec** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #6099** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6099?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #6100** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6100?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #6107** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6107?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #6108** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108?utm_source=stack-comment).

**Comment by buffalojoec** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #6099** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6099?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #6100** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6100?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #6107** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6107?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #6108** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108?utm_source=stack-comment).

File: token/js/src/extensions/transferHook/instructions.ts [hunk 1]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
...
+ * @param validateStatePubkey   The validate state pubkey
+ * @param amount                The amount of tokens to transfer
+ * @returns Instruction to add to a transaction
+ */
+export function createExecuteInstruction(
+    programId: PublicKey,
+    source: PublicKey,
+    mint: PublicKey,
+    destination: PublicKey,
+    authority: PublicKey,
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:212]: micro-nit: we use the term `owner` everywhere else in the library, and even the comment for this function uses `owner`

File: token/js/src/extensions/transferHook/instructions.ts [hunk 2]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
...
+    validateStatePubkey: PublicKey,
+    amount: number | bigint
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:214]: nit: since this is new, what do you think about only supporting `bigint`?

File: token/js/src/extensions/transferHook/instructions.ts [hunk 3]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
     return new TransactionInstruction({ keys: accountMetas, programId, data: instruction.data });
 }
 
+/**
+ * Construct an `ExecuteInstruction` for a transfer hook program
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:196]: nit: just to make it clear what this function is meant for:
```suggestion
 * Construct an `ExecuteInstruction` for a transfer hook program, without the additional accounts
```

File: token/js/src/extensions/transferHook/instructions.ts [hunk 4]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
...
+/**
+ * Adds all the extra accounts needed for a transfer hook to an instruction
+ *
+ * @param connection            Connection to use
+ * @param instruction           The instruction to add accounts to
+ * @param programId             Transfer hook program ID
+ * @param source                The source account
+ * @param mint                  The mint account
+ * @param destination           The destination account
+ * @param authority             Owner of the source account
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:238]: micro-nit: same here, maybe use `owner` for consistency?

File: token/js/src/extensions/transferHook/instructions.ts [hunk 5]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
...
+ * @returns A new instruction with the extra account metas added
+ */
+export async function addExtraAccountMetasForExecute(
+    connection: Connection,
+    instruction: TransactionInstruction,
+    programId: PublicKey,
+    source: PublicKey,
+    mint: PublicKey,
+    destination: PublicKey,
+    authority: PublicKey,
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:250]: micro-nit: and same here, `owner`?

File: token/js/src/extensions/transferHook/instructions.ts [hunk 6]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
...
+
 /**
  * Construct an transferChecked instruction with extra accounts for transfer hook
  *
  * @param connection            Connection to use
  * @param source                Source account
  * @param mint                  Mint to update
  * @param destination           Destination account
- * @param authority             The mint's transfer hook authority
+ * @param authority             Owner of the source account
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:308]: Oh never mind, we're using `authority` in this file, so I'll leave it up to you

File: token/js/src/extensions/transferHook/instructions.ts [hunk 7]
```diff
@@ -190,14 +192,120 @@ export async function addExtraAccountsToInstruction(
...
+    }
+
+    // Add only the extra accounts resolved from the validation state
+    instruction.keys.push(...executeInstruction.keys.slice(5));
+
+    // Add the transfer hook program ID and the validation state account
+    instruction.keys.push({ pubkey: programId, isSigner: false, isWritable: false });
+    instruction.keys.push({ pubkey: validateStatePubkey, isSigner: false, isWritable: false });
+
+    return instruction;
```
Comment (joncinque) [inline token/js/src/extensions/transferHook/instructions.ts:298]: nit: This is modifying the instruction in-place and also returning it, which could be confusing since the Rust side is only modifying the instruction in-place.

For consistency, it would probably be better for this function to only modify the instruction and not return it.

File: token/js/test/unit/transferHook.test.ts [hunk 8]
```diff
@@ -1,173 +1,547 @@
...
+            expect(parsedExtraAccounts[0].addressConfig).to.eql(plainAccount.toBuffer());
+            expect(parsedExtraAccounts[0].isSigner).to.be.false;
+            expect(parsedExtraAccounts[0].isWritable).to.be.false;
+
+            expect(parsedExtraAccounts[1].discriminator).to.eql(1);
+            expect(parsedExtraAccounts[1].addressConfig).to.eql(addressConfig);
+            expect(parsedExtraAccounts[1].isSigner).to.be.true;
+            expect(parsedExtraAccounts[1].isWritable).to.be.false;
+
+            expect(parsedExtraAccounts[2].discriminator).to.eql(128);
```
Comment (joncinque) [inline token/js/test/unit/transferHook.test.ts:155]: side note: I had totally forgotten about using the higher bits for the program id to use on the PDA, we'll definitely need that documented somewhere too

File: token/js/test/unit/transferHook.test.ts [hunk 9]
```diff
@@ -1,173 +1,547 @@
...
         });
     });
 
-    it('getExtraAccountMetas', () => {
-        const accountInfo = {
-            data: extraAccountList,
-            owner: PublicKey.default,
-            executable: false,
-            lamports: 0,
+    // prettier-ignore
```
Comment (joncinque) [inline token/js/test/unit/transferHook.test.ts:200]: Why is this needed?

File: token/js/test/unit/transferHook.test.ts [hunk 10]
```diff
@@ -1,173 +1,547 @@
...
+            const decimals = 0;
+
+            // Arbitrary program ID included to test external PDAs
+            const arbitraryProgramId = Keypair.generate().publicKey;
+
+            const connection = await getConnection();
+            connection.getAccountInfo = async function mockFetchAccountDataFn(
+                publicKey: PublicKey,
+                _commitmentOrConfig?: Parameters<Connection['getAccountInfo']>[1]
+            ): ReturnType<Connection['getAccountInfo']> {
```
Comment (joncinque) [inline token/js/test/unit/transferHook.test.ts:391]: nit: this function is pretty big, and very similar to the one in the previous test -- you could initialize all of the keys one level up and move this function up one level to be re-used by both tests, which would probably make this test more legible too.

**Review by joncinque — COMMENTED** [review]
Just nits really, the whole thing looks great!

File: token/js/test/unit/transferHook.test.ts (hunk 9 above)
Comment (buffalojoec) [reply token/js/test/unit/transferHook.test.ts:200]: It nukes my bytes and comments below. I placed it up here when I had the tests with those large byte layouts, but now I can move it to the variable itself.

File: token/js/src/extensions/transferHook/instructions.ts [hunk 11]
```diff
@@ -137,6 +137,8 @@ function deEscalateAccountMeta(accountMeta: AccountMeta, accountMetas: AccountMe
 }
 
 /**
+ * @deprecated Deprecated since v0.4.0. Please use {@link addExtraAccountMetasForExecute} instead.
```
[the remark this answers is not in the document]
Comment (buffalojoec) [reply token/js/src/extensions/transferHook/instructions.ts:140]: Oops my bad.

File: token/js/src/extensions/transferHook/instructions.ts (hunk 6 above)
Comment (buffalojoec) [reply token/js/src/extensions/transferHook/instructions.ts:308]: Heh, it's `owner` on all of the transfer instructions, but it's `authority` in SPL Transfer Hook. I think it may make the most sense to use `owner` on the transfer instructions here, but `authority` on the one that creates an `ExecuteInstruction`.

Comment (joncinque) [reply token/js/src/extensions/transferHook/instructions.ts:308]: to be honest, I think that might be more confusing, since the execute instruction is supposed to be using the same `owner` on the token account

Comment (buffalojoec) [reply token/js/src/extensions/transferHook/instructions.ts:308]: Alright I'm just going to go with `owner` then.

File: token/js/test/unit/transferHook.test.ts (hunk 8 above)
Comment (buffalojoec) [reply token/js/test/unit/transferHook.test.ts:155]: Yeah, the constructors like `new_with_external_pda(..)` aren't in the JS lib since it's designed for reading extra meta configs. Creating them is pretty manual atm.

I'm assuming you mean document that in the Transfer Hook docs? Or do you mean in this library?

Comment (joncinque) [reply token/js/test/unit/transferHook.test.ts:155]: Right, makes sense. and correct, I mean in the transfer hook docs, since JS lib users probably don't need to know about it

File: token/js/test/unit/transferHook.test.ts [hunk 12]
```diff
@@ -1,173 +1,534 @@
...
+                };
+            }
+
+                return {
+                    data: Buffer.from([]),
+                    owner: PublicKey.default,
+                    executable: false,
+                    lamports: 0,
+                };
+            };
```
Comment (joncinque) [inline token/js/test/unit/transferHook.test.ts:303]: I'm not sure if it's good to use prettier-ignore here, since it made this part harder to read. Is there any way to fixup the spacing or object declarations so that it plays well with prettier?

**Review by joncinque — DISMISSED** [review]
Just one last little nit, but otherwise feel free to merge once it's resolved!

File: token/js/test/unit/transferHook.test.ts (hunk 12 above)
Comment (buffalojoec) [reply token/js/test/unit/transferHook.test.ts:303]: I can take it out there. I really only wanted it where the raw bytes are. This is what it looks like if I take it out:

```ts
if (publicKey.equals(validateStatePubkey)) {
    const extraAccountsList: ExtraAccountMetaList = {
        count: extraAccounts.length,
        extraAccounts,
    };
    const instructionDiscriminator = Buffer.from([
        105, 37, 101, 197, 75, 251, 102, 26,
    ]).readBigUInt64LE();
    const data = Buffer.alloc(8 + 4 + 4 + ExtraAccountMetaLayout.span * extraAccounts.length);
    ExtraAccountMetaAccountDataLayout.encode(
        {
            instructionDiscriminator,
            length: 4 + ExtraAccountMetaLayout.span * extraAccounts.length,
            extraAccountsList,
        },
        data
    );
    return {
        data,
        owner: transferHookProgramId,
        executable: false,
        lamports: 0,
    };
}
```

Comment (buffalojoec) [reply token/js/test/unit/transferHook.test.ts:303]: It's *a little* easier to read, ha 😅, wdyt?

**Comment by buffalojoec** [comment]
### Merge activity

* **Jan 11, 4:15 PM**: @buffalojoec started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-program-library/6108).

File: token/js/test/unit/transferHook.test.ts (hunk 12 above)
Comment (joncinque) [reply token/js/test/unit/transferHook.test.ts]: Yeah that's better!
