### PR TITLE
Reinstate Mint supply

### LINKED ISSUE #328: token: require all token accounts be rent-exempt and restore total supply field in the mint
We lost the total supply field in the mint when we realized that if token accounts aren't created rent-exempt, they could just disappear and cause the total supply to be inflated.

However we've failed to discover a compelling reason to permit non-rent-exempt token accounts.  Additionally with the new `CloseAccount` instruction, you can reclaim your SOL from a token account at any time.

Requiring rent exemption also simplifies wallets and other token clients, as they no longer need to be considered about a token account disappearing because it was underfunded, either by accident or maliciously.

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Reinstate the `supply` field to the `Mint` state, and adjust on MintTo and Burn instructions. Reinstate passing the mint account into Burn instructions.

Also cleaned up a couple account ordered lists in docs

Fixes #328

### CODE REVIEW

File: token/program/src/state.rs [hunk 1]
```diff
@@ -12,6 +12,8 @@ pub struct Mint {
     /// mint creation. If no mint authority is present then the mint has a fixed supply and no
     /// further tokens may be minted.
     pub mint_authority: COption<Pubkey>,
+    /// Total supply of tokens.
+    pub supply: u64,
```
Comment (mvines) [inline token/program/src/state.rs:16]: So happy to see this back

File: token/program/src/processor.rs [hunk 2]
```diff
@@ -439,6 +451,7 @@ impl Processor {
         }
 
         source_account.amount -= amount;
+        mint.supply -= amount;
```
Comment (mvines) [inline token/program/src/processor.rs:454]: In a follow-up PR, can you please replace all the `-=` with `checked_sub()`.  Let's just use checked math everywhere in the program, even when it's obviously not necessary

**Review by mvines — DISMISSED** [review]

File: token/cli/src/main.rs [hunk 3]
```diff
@@ -213,12 +213,20 @@ fn command_burn(config: &Config, source: Pubkey, ui_amount: f64) -> CommmandResu
         .rpc_client
         .get_token_account_balance_with_commitment(&source, config.commitment_config)?
         .value;
+    let source_account = config
```
Comment (mvines) [inline token/cli/src/main.rs:216]: `source_token_balance` is only used to figure decimals, which we can get from the mint.  So I think we can remove the `get_token_account_balance_with_commitment()` RPC call entirely

Comment (CriesofCarrots) [reply token/cli/src/main.rs:216]: Still two calls, since we'll have to pull the mint.

Comment (mvines) [reply token/cli/src/main.rs:216]: ah, yeah ok.  wfm
