### PR TITLE
associated-token-account: Add "CreateIdempotent" instruction

### LINKED ISSUE #2295: ATA create transaction race
#### Problem

Dapps that submit frequent consecutive transactions referencing the same ATA race when the account needs to be created.  This leads to subsequent transactions failing

#### Proposed Solution

Allow ATA create to succeed without effects if the account already exists in the expected state, perhaps via an explicit instruction

### PR DESCRIPTION
**Pull request by joncinque**
Fixes #2295

#### Problem

Lots of ATA transactions fail because they all try to create the account.

#### Solution

Add a `CreateIfNonExistent` instruction. I'm up for any better names!

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]
Generally lgtm!
A dedupe suggestion and a little bikeshedding.

File: associated-token-account/program/tests/create_if_non_existent.rs [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+    let associated_account = banks_client
+        .get_account(associated_token_address)
+        .await
+        .expect("get_account")
+        .expect("associated_account not none");
+    assert_eq!(associated_account.data.len(), expected_token_account_len);
+    assert_eq!(associated_account.owner, spl_token::id());
+    assert_eq!(associated_account.lamports, expected_token_account_balance);
+
+    // Old instruction fails
```
Comment (t-nelson) [inline associated-token-account/program/tests/create_if_non_existent.rs:70]:
```suggestion
    // Unchecked instruction fails
```

File: associated-token-account/program/src/processor.rs [hunk 2]
```diff
@@ -56,6 +70,21 @@ pub fn process_create_associated_token_account(
     let spl_token_program_info = next_account_info(account_info_iter)?;
     let spl_token_program_id = spl_token_program_info.key;
 
+    if create_mode == CreateMode::IfNonExistent
+        && associated_token_account_info.owner == spl_token_program_id
+    {
+        let ata_data = associated_token_account_info.data.borrow();
+        if let Ok(associated_token_account) = StateWithExtensions::<Account>::unpack(&ata_data) {
+            if associated_token_account.base.owner != *wallet_account_info.key {
+                return Err(ProgramError::IllegalOwner);
```
Comment (t-nelson) [inline associated-token-account/program/src/processor.rs:79]: This error is meant for an unexpected `AccountInfo::owner`.  I'm not sure it's a good idea to overload it here with program-specific meaning.

File: associated-token-account/program/src/processor.rs [hunk 3]
```diff
@@ -56,6 +70,21 @@ pub fn process_create_associated_token_account(
     let spl_token_program_info = next_account_info(account_info_iter)?;
     let spl_token_program_id = spl_token_program_info.key;
 
+    if create_mode == CreateMode::IfNonExistent
+        && associated_token_account_info.owner == spl_token_program_id
```
Comment (t-nelson) [inline associated-token-account/program/src/processor.rs:74]: I think we should explicitly return `ProgramError::IllegalOwner` in the contra case for the sake of hardening against future errors

File: associated-token-account/program/src/instruction.rs [hunk 4]
```diff
@@ -22,9 +22,20 @@ pub enum AssociatedTokenAccountInstruction {
...
+    /// if it doesn't already exist.  Returns an error if the account exists,
+    /// but with a different owner.
+    ///
+    ///   0. `[writeable,signer]` Funding account (must be a system account)
+    ///   1. `[writeable]` Associated token account address to be created
+    ///   2. `[]` Wallet address for the new associated token account
+    ///   3. `[]` The token mint for the new associated token account
+    ///   4. `[]` System program
+    ///   5. `[]` SPL Token program
+    CreateIfNonExistent,
```
[the remark this answers is not in the document]
Comment (t-nelson) [reply associated-token-account/program/src/instruction.rs:35]: `EnsureOrCreate`? `CreateIfMissing`?  (mostly just bikeshedding because it's kind of a mouthful ATM)

**Review by t-nelson — COMMENTED** [review]
Looking good!  Just a little pedantry from me

File: associated-token-account/program/src/processor.rs (hunk 3 above)
Comment (t-nelson) [reply associated-token-account/program/src/processor.rs:74]: Sorry, _errors_ is ambiguous here. I mean _programming_ errors :wink:

File: associated-token-account/program/src/instruction.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (mvines) [reply associated-token-account/program/src/instruction.rs:35]: 🚴🏼‍♂️ I think I favour a terse `CreateIf` myself.

File: associated-token-account/program/src/processor.rs (hunk 3 above)
Comment (joncinque) [reply associated-token-account/program/src/processor.rs:74]: Which contra case do you mean exactly?  If `associated_token_account_info.owner != spl_token_program_id`, that's still valid, because it'll be `system_program::id()` if the account hasn't been created. Do you mean for it to go:
```
if create_mode == ... {
    if ata.owner == spl_token_program_id {
        ...
    } else if ata.owner != system_program::id() {
        return Err(ProgramError::IllegalOwner);
    }
}
```

Comment (t-nelson) [reply associated-token-account/program/src/processor.rs]: Yep! That's the logic I'd like to make prominent

File: associated-token-account/program/src/error.rs [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+use {
+    num_derive::FromPrimitive,
+    solana_program::{decode_error::DecodeError, program_error::ProgramError},
+    thiserror::Error,
+};
+
+/// Errors that may be returned by the program.
+#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
+pub enum AssociatedTokenAccountError {
+    // 0
```
Comment (CriesofCarrots) [inline associated-token-account/program/src/error.rs:12]: I sure hope we don't end up with enough error variants to need this...

File: associated-token-account/program/src/processor.rs [hunk 6]
```diff
@@ -56,6 +72,26 @@ pub fn process_create_associated_token_account(
...
+                    return Err(error.into());
+                }
+                if associated_token_account.base.mint != *spl_token_mint_info.key {
+                    return Err(ProgramError::InvalidAccountData);
+                }
+                return Ok(());
+            }
+        } else if *associated_token_account_info.owner != system_program::id() {
+            return Err(ProgramError::IllegalOwner);
+        }
```
Comment (CriesofCarrots) [inline associated-token-account/program/src/processor.rs:92]: I dunno, do we really need this? And if so, why is it specific to CreateMode::Idempotent?
Aren't `associated_token_account_info.owner != system_program::id()` cases just going to error out in `create_pda_account()` when the invokes are attempted?

Comment (t-nelson) [reply associated-token-account/program/src/processor.rs:92]: It's more about making the check clear in the code so future modifications don't introduce errors.  Relying on another method to do the right thing is how wormhole was exploited.

I'd be fine with moving it above the instruction variant check though

File: associated-token-account/program/src/error.rs (hunk 5 above)
Comment (joncinque) [reply associated-token-account/program/src/error.rs:12]: If it saves even one question of "Associated Token Program has custom error 0x0, what does that mean?", it'll be more than worth it!

File: associated-token-account/program/src/processor.rs (hunk 6 above)
Comment (CriesofCarrots) [reply associated-token-account/program/src/processor.rs:92]: Yes, well, if the System Program breaks that badly, I'm not sure this will be the biggest of our problems.

File: associated-token-account/program/src/error.rs (hunk 5 above)
Comment (CriesofCarrots) [reply associated-token-account/program/src/error.rs:12]: Hehe, fair enough!

File: associated-token-account/program/src/processor.rs (hunk 6 above)
Comment (CriesofCarrots) [reply associated-token-account/program/src/processor.rs:92]: Your call, @joncinque . But I think it needs to be outside the instruction variant case, though (and after seems less of a pita than before)

Comment (joncinque) [reply associated-token-account/program/src/processor.rs:92]: It costs very little to add in outside this check, so I'll move it

**Comment by joncinque** [comment]
Any other concerns here? Everything has been addressed

**Review by CriesofCarrots — APPROVED** [review]
:shipit:

File: associated-token-account/program/src/processor.rs [hunk 7]
```diff
@@ -56,6 +72,26 @@ pub fn process_create_associated_token_account(
...
+                msg!("{}", error);
+                return Err(error.into());
+            }
+            if associated_token_account.base.mint != *spl_token_mint_info.key {
+                return Err(ProgramError::InvalidAccountData);
+            }
+            return Ok(());
+        }
+    }
+    if *associated_token_account_info.owner != system_program::id() {
```
Comment (ryoqun) [inline associated-token-account/program/src/processor.rs:91]: ... so, we start to disallow atas for multisigs, maybe?

File: associated-token-account/program/src/processor.rs [hunk 8]
```diff
@@ -56,6 +72,26 @@ pub fn process_create_associated_token_account(
...
+        let ata_data = associated_token_account_info.data.borrow();
+        if let Ok(associated_token_account) = StateWithExtensions::<Account>::unpack(&ata_data) {
+            if associated_token_account.base.owner != *wallet_account_info.key {
+                let error = AssociatedTokenAccountError::InvalidOwner;
+                msg!("{}", error);
+                return Err(error.into());
+            }
+            if associated_token_account.base.mint != *spl_token_mint_info.key {
+                return Err(ProgramError::InvalidAccountData);
+            }
```
Comment (ryoqun) [inline associated-token-account/program/src/processor.rs:87]: is there any reason we don't check `associated_token_address == *associated_token_account_info.key`? maybe to save compute? strictly speaking this is breaking the idempotent? (i.e. you can get false-positive (Ok from CreateIdempotent) for arbitrary existing non-ata accounts)

Comment (joncinque) [reply associated-token-account/program/src/processor.rs:87]: That's a great point, I'll move that check up

File: associated-token-account/program/src/processor.rs (hunk 7 above)
Comment (eulerbeat) [reply associated-token-account/program/src/processor.rs:91]: got what u mean, this prevents the error when you are trying to create ATA that is already created
