### PR TITLE
Token cli: Improve authorize command

### LINKED ISSUE #791: spl-token-cli: Unhelpful error message when authorizing setting incompatible authority for account type
## Problem

`spl-token authorize` emits an unhelpful error when the specified `AUTHORITY_TYPE` is incompatible with the specified `TOKEN_ADDRESS`

```
RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xf
```

## Suggested changes

1. Client-side check compatibility of authority type and account type
2. Genericize `TOKEN_ADDRESS` positional param name and help messages, as the subcommand supports both token accounts and mints

### LINKED ISSUE #1431: Token cli: easy to authorize away ATA
Wallets should not allow the user to authorize an ATA to another address. But `spl-token authorize` does this happily.
Make it really difficult, or prevent entirely.

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Several changes to remove footguns and make failure debugging easier for `spl-token authorize` commands.
- Check target account type (mint vs. account) and return clear error message if authorize is attempting to change an incompatible authority type
- Print the real current authority to make it easier to detect if `--owner` is incorrect authority for operation
- Refuse to change the owner or close authority if the account is an ATA of the `--owner`; hidden `--force` arg overrides

Fixes #791 
Fixes #1431

### CODE REVIEW

File: token/cli/src/main.rs [hunk 1]
```diff
@@ -365,18 +366,67 @@ fn command_authorize(
...
+    } else if let Ok(token_account) = Account::unpack(&target_account.data) {
+        let check_associated_token_account = || -> Result<(), Error> {
+            let maybe_associated_token_account =
+                get_associated_token_address(&config.owner, &token_account.mint);
+            if account == maybe_associated_token_account
+                && !force_authorize
+                && Some(config.owner) != new_owner
+            {
+                Err(
+                    format!("Error: attmepting to change the `{}` of an associated token account of `--owner`", auth_str)
```
Comment (t-nelson) [inline token/cli/src/main.rs:396]:
```suggestion
                    format!("Error: attempting to change the `{}` of an associated token account of `--owner`", auth_str)
```

File: token/cli/src/main.rs [hunk 2]
```diff
@@ -365,18 +366,67 @@ fn command_authorize(
...
         AuthorityType::MintTokens => "mint authority",
         AuthorityType::FreezeAccount => "freeze authority",
         AuthorityType::AccountOwner => "owner",
         AuthorityType::CloseAccount => "close authority",
     };
+    let target_account = config.rpc_client.get_account(&account)?;
+    let previous_authority = if let Ok(mint) = Mint::unpack(&target_account.data) {
+        match authority_type {
+            AuthorityType::AccountOwner | AuthorityType::CloseAccount => Err(format!(
+                "Authority type `{}` not supported for mints",
```
Comment (t-nelson) [inline token/cli/src/main.rs:381]: NIT

```suggestion
                "Authority type `{}` not supported for SPL Token mints",
```

File: token/cli/src/main.rs [hunk 3]
```diff
@@ -365,18 +366,67 @@ fn command_authorize(
...
+                        .into(),
+                )
+            } else {
+                Ok(())
+            }
+        };
+
+        match authority_type {
+            AuthorityType::MintTokens | AuthorityType::FreezeAccount => Err(format!(
+                "Authority type `{}` not supported for accounts",
```
Comment (t-nelson) [inline token/cli/src/main.rs:406]: NIT

```suggestion
                "Authority type `{}` not supported for SPL Token accounts",
```

**Review by t-nelson — APPROVED** [review]
LGTM with typo fix.  I also added a couple nits in the spirit of the native/SPL Token "account" discussion in #terminology on Discord

**Comment by CriesofCarrots** [comment]
Merging on red. This one passed CI here: https://github.com/solana-labs/solana-program-library/actions/runs/650491355
Only subsequent changes were to print text.
