### PR TITLE
Clone signers

### LINKED ISSUE #2668: token-cli: issues when sending keypair data via STDIN
This is a follow up from https://github.com/solana-labs/solana/issues/21811 where the intent is to pass keypair data via STDIN to `spl-token` CLI. It seems that the behavior or keypair coming in from STDIN is not as seamless as that coming from a file leading to a workflow that breaks during `spl-token mint`.

If the config file, named `stdin.yaml`, is defined as follows, indicating keypair coming in from STDIN.
```yaml
json_rpc_url: "http://localhost:8899"
websocket_url: ""
keypair_path: "stdin:"
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
```
and let's assume that a keypair exists in a file called `id.json`, then 

```
└─ $ ▶ cat ~/.config/solana/id.json | solana-keygen pubkey --config ~/.config/solana/cli/stdin.yaml
FTS7wJf5NPqFBqbmBCeCpP8pGZoQkRxG6ug22C8wj8Zv
```

token creation went fine after explicitly passing --mint-authority 
```
└─ $ ▶ cat ~/.config/solana/id.json | spl-token create-token --mint-authority=FTS7wJf5NPqFBqbmBCeCpP8pGZoQkRxG6ug22C8wj8Zv --config ~/.config/solana/cli/stdin.yaml
Creating token F8qXgouoUUdsoQF2iDT7JvEozaoJs3rq9icZUKhukNUf

Signature: 5YKg5uRFSiXe6Xq1xtd1N4cPCX63E5NcXJtd8wkTfsfmPW6zfjCyje1ktFQhLLcUWDsmdCE8WoMcA1EBVeohFiCT
```

but minting failed
```
└─ $ ▶ cat ~/.config/solana/id.json | spl-token mint F8qXgouoUUdsoQF2iDT7JvEozaoJs3rq9icZUKhukNUf 100 --config ~/.config/solana/cli/stdin.yaml
error: EOF while parsing a value at line 1 column 0
```

explicitly providing `--mint-authority` leads to another error as follows:
```
└─ $ ▶ cat ~/.config/solana/id.json | spl-token mint F8qXgouoUUdsoQF2iDT7JvEozaoJs3rq9icZUKhukNUf 100 --config ~/.config/solana/cli/stdin.yaml --mint-authority=FTS7wJf5NPqFBqbmBCeCpP8pGZoQkRxG6ug22C8wj8Zv
error: missing signature for supplied pubkey: FTS7wJf5NPqFBqbmBCeCpP8pGZoQkRxG6ug22C8wj8Zv
```

It seems that `spl-token` is not honoring keypair input via STDIN properly. I would have expected it to behave similarly to the case when keypair input is from a file. In particular, when keypair input is from a file, `spl-token create-token` and `spl-token mint` commands work without requiring additional flags.

Thanks in advance for support on this issue. Allowing STDIN input for keypair enabled encrypted wallets and prevents persisting of keys on the disk in plaintext.

### PR DESCRIPTION
**Pull request by jmalcic**
This PR fixes #2668 by not attempting to read signers more than once. Because signers are trait objects, and so unsized, the approach here is to clone a pointer which will point to the same object in memory, not the data on the heap itself. This requires a change from `Box` to `Rc` or `Arc`, and I've gone with `Arc`. This requires corresponding changes in [solana-labs/solana](https://github.com/solana-labs/solana), so there's a temporary commit 89a6afe1ea991801ad2f7c0b91f858e5f1001d21 to allow testing, which needs to be reverted before the PR is merged (hence the WIP). I've stored the `Arc`s in the config struct just for convenience elsewhere; unfortunately they're needed to construct some of the other struct fields, so some of the stuff that was in `config.rs` has now moved into `main.rs`—if there's a better way of organising this, I'd be happy to make changes. I haven't dealt here with commands other than the behaviour in #2668 described with `mint`, but the PR could be expanded a bit if this was desired—it looks like getting the nonce authority could cause the same problem with rereading the signer for instance (so requiring a change like ef8a27b264bf3accc049671ad8fcbc64d68e5ca6).

### CODE REVIEW

File: token/cli/src/bench.rs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+use solana_sdk::signature::{Signature, SignerError};
+use solana_sdk::signers::Signers;
```
Comment (joncinque) [inline token/cli/src/bench.rs:2]: nit: let's move these imports down into the one bigger statement

File: token/cli/src/bench.rs [hunk 2]
```diff
@@ -19,6 +21,47 @@ use {
     std::{sync::Arc, time::Instant},
 };
 
+struct CustomSigner(Vec<Arc<dyn solana_sdk::signature::Signer>>);
```
Comment (joncinque) [inline token/cli/src/bench.rs:24]: nit: how about we call this `ArcSigner` so we totally know what it's for?

File: token/cli/src/bench.rs [hunk 3]
```diff
@@ -19,6 +21,47 @@ use {
     std::{sync::Arc, time::Instant},
 };
```
Comment (joncinque) [inline token/cli/src/bench.rs:23]: Could you put in a PR to the monorepo to add the implementation for `Vec<Arc<dyn Signer>>` and `[Arc<dyn Signer>]`? Please tag me on it too.  Then please add a comment here saying to remove this signer implementation once that PR is available in the SDK.

File: token/cli/src/config.rs [hunk 4]
```diff
@@ -22,6 +22,8 @@ pub(crate) enum KeypairOrPath {
 }
 
 pub(crate) struct Config<'a> {
+    pub(crate) default_signer: Arc<dyn Signer>,
+    pub(crate) default_address: Pubkey,
     pub(crate) rpc_client: Arc<RpcClient>,
     pub(crate) websocket_url: String,
     pub(crate) output_format: OutputFormat,
```
Comment (joncinque) [inline token/cli/src/config.rs:29]: I can't comment further down, but with this change, it doesn't seem like we even need `default_keypair` anymore! Let's remove it

File: token/cli/src/config.rs [hunk 5]
```diff
@@ -22,6 +22,8 @@ pub(crate) enum KeypairOrPath {
 }
 
 pub(crate) struct Config<'a> {
+    pub(crate) default_signer: Arc<dyn Signer>,
+    pub(crate) default_address: Pubkey,
```
Comment (joncinque) [inline token/cli/src/config.rs:26]: Since `default_address` is just `default_signer.pubkey()`, how about we get rid of it and rederive the pubkey whenever needed?

**Review by joncinque — COMMENTED** [review]
This is definitely on the right track! #3293 will refactor some of this, so we'll have to merge these all carefully

**Comment by jmalcic** [comment]
The tests for transferring and burning with a delegate are now failing but I'm pushing anyway. As far as I can tell the delegate is being ignored because transferring more than has been approved doesn't fail. I can see that the instructions in the case with and without the delegate do differ as expected—only in the case with the delegate are there two separate addresses for the source and the owner

File: token/cli/src/config.rs [hunk 6]
```diff
@@ -91,17 +91,12 @@ impl<'a> Config<'a> {
 
     pub(crate) fn associated_token_address_for_token_and_program(
         &self,
-        arg_matches: &ArgMatches<'_>,
-        wallet_manager: &mut Option<Arc<RemoteWalletManager>>,
+        _arg_matches: &ArgMatches<'_>,
+        _wallet_manager: &mut Option<Arc<RemoteWalletManager>>,
```
Comment (joncinque) [inline token/cli/src/config.rs:95]: Feel free to remove these parameters if they're unused

**Review by joncinque — COMMENTED** [review]
Really great work! Just take care of the cargo fmt and clippy bits, then this will be ready to go

File: token/cli/src/bench.rs (hunk 3 above)
Comment (jmalcic) [reply token/cli/src/bench.rs:31]: PR is now open: https://github.com/solana-labs/solana/pull/27000

**Comment by jmalcic** [comment]
I'm not clear why clippy is giving these errors, as far as I can see the build fails without the imports

File: token/cli/src/main.rs [hunk 7]
```diff
@@ -54,7 +53,7 @@ use std::{
 use strum_macros::{EnumString, IntoStaticStr, ToString};
 
 mod config;
-use config::{Config, KeypairOrPath, MintInfo};
+use config::{Config, MintInfo};
```
Comment (joncinque) [inline token/cli/src/main.rs:56]: Since these creators were moved, you need to get rid of the imports for `ProgramRpcClient*` in this file as mentioned by clippy just above

Comment (jmalcic) [reply token/cli/src/main.rs:56]: Whoops sorry it's that they should be in the `tests` module for the test config

**Comment by joncinque** [comment]
Great work, thanks for the contribution!
